baseURL = "https://blog.ojakee.com/"
title = "Ojakee Parenting Blog"
languageCode = "en-us"
theme = "PaperMod"
enableGitInfo = true
enableEmoji = true
enableRSS = true
enableSitemap = true
enableSitemapIndex = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  author = "Ojakee Team"
  description = "Parenting insights to help your children thrive more than ever."
  ddefaultTheme = "auto"  
  disableThemeToggle = false
  ShowThemeToggleInHeader = true 
  ShowReadingTime = true
  ShowWordCount = true
  ShowReadingProgress = true
  ShowToc = true
  TocOpen = true  
  TocSide = "right"  
  ShowShareButtons = true
  ShareButtonsPosition = "side"
  ShowBreadCrumbs = true 
  ShowPostNavLinks = true 
  comments = false
  [params.label]
    icon = "/images/logo.png"
    iconHeight = 35
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    minMatchCharLength = 2
    keys = ["title", "content", "tags", "categories"]
  [params.assets]
    favicon = "/images/logo.png"
    favicon16x16 = "/images/logo.png"
    favicon32x32 = "/images/logo.png"
    apple_touch_icon = "/images/logo.png"
    lightbox = true

[params.homeInfoParams]
  Title = "Welcome to the Ojakee Blog"
  Content = "Evidence-based tips, charts, and real stories to support your parenting journey"

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Series"
  url = "/series/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Try Our App"
  url = "https://ojakee.com"
  weight = 4

[markup.goldmark.renderer]
  # This is to allow raw HTML in markdown files. Required for charts.
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

